CREATE TABLE cms.translations (
 slug text NOT NULL REFERENCES cms.pages ON DELETE CASCADE, locale text NOT NULL REFERENCES core.locales, title text NOT NULL DEFAULT '', summary text NOT NULL DEFAULT '', body text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','queued','translated','approved','published','failed')), source_locale text NOT NULL REFERENCES core.locales, version bigint NOT NULL DEFAULT 1, updated_at timestamptz NOT NULL DEFAULT now(), translated_by text NOT NULL DEFAULT 'human', PRIMARY KEY(slug,locale)
);
CREATE TABLE cms.translation_jobs (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL REFERENCES cms.pages ON DELETE CASCADE, source_locale text NOT NULL REFERENCES core.locales, target_locale text NOT NULL REFERENCES core.locales, source_version bigint NOT NULL, provider text NOT NULL DEFAULT 'configured_ai', status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','completed','failed','cancelled')), attempts int NOT NULL DEFAULT 0, error text, created_by uuid NOT NULL REFERENCES auth.users, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(slug,source_version,source_locale,target_locale)
);
ALTER TABLE cms.translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE cms.translation_jobs ENABLE ROW LEVEL SECURITY;
INSERT INTO cms.translations(slug,locale,title,summary,body,status,source_locale,translated_by) SELECT slug,'tr',title,summary,body,CASE WHEN published IS NULL THEN 'draft' ELSE 'published' END,'tr','seed' FROM cms.pages ON CONFLICT(slug,locale) DO NOTHING;
CREATE FUNCTION cms.translate_all(p_slug text,p_source text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$ DECLARE p cms.pages%ROWTYPE; l text; BEGIN IF NOT cms.can_edit() OR p_source NOT IN ('tr','en','de','ru','ar','fr') THEN RETURN 'forbidden'; END IF; SELECT * INTO p FROM cms.pages WHERE slug=p_slug; IF NOT FOUND THEN RETURN 'not_found'; END IF; FOREACH l IN ARRAY ARRAY['tr','en','de','ru','ar','fr'] LOOP IF l<>p_source THEN INSERT INTO cms.translation_jobs(slug,source_locale,target_locale,source_version,created_by) VALUES(p_slug,p_source,l,p.version,nullif(current_setting('app.actor_id',true),'')::uuid) ON CONFLICT DO NOTHING; INSERT INTO cms.translations(slug,locale,source_locale,status,version,translated_by) VALUES(p_slug,l,p_source,'queued',p.version,'ai_pending') ON CONFLICT(slug,locale) DO UPDATE SET status='queued',source_locale=EXCLUDED.source_locale,version=EXCLUDED.version,updated_at=now(); END IF; END LOOP; RETURN 'translation_queued'; END $$;
CREATE FUNCTION cms.translation_status() RETURNS TABLE(data text[]) LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT ARRAY[j.slug,j.source_locale,j.target_locale,j.status,j.provider,j.attempts::text,coalesce(j.error,'')] FROM cms.translation_jobs j WHERE cms.can_edit() ORDER BY j.created_at DESC LIMIT 300 $$;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA cms FROM PUBLIC;
GRANT EXECUTE ON FUNCTION cms.translate_all(text,text),cms.translation_status() TO nexus_app;
