-- Shared category service-step contract. Runtime tasks remain local to each system.
CREATE TABLE IF NOT EXISTS onboarding.category_service_steps (
  category_code text NOT NULL,
  step_key text NOT NULL,
  stage text NOT NULL CHECK(stage IN ('before','during','after')),
  title_tr text NOT NULL,
  owner_role text NOT NULL CHECK(owner_role IN ('admin','supplier')),
  position integer NOT NULL,
  contract_version text NOT NULL DEFAULT '1.0.0',
  PRIMARY KEY(category_code,step_key)
);
INSERT INTO onboarding.category_service_steps(category_code,step_key,stage,title_tr,owner_role,position) VALUES
 ('hotel','room_ready','before','Oda ve giriş bilgisini doğrula','supplier',10),
 ('hotel','checkin','during','Giriş ve konaklama talebini izle','supplier',20),
 ('hotel','checkout','after','Çıkış ve konaklama belgesini tamamla','supplier',30),
 ('holiday_home','property_ready','before','Ev, temizlik ve anahtar teslimini doğrula','supplier',10),
 ('holiday_home','arrival','during','Giriş ve ev kurallarını misafire ilet','supplier',20),
 ('holiday_home','deposit_return','after','Depozito ve çıkış kontrolünü tamamla','supplier',30),
 ('yacht','vessel_ready','before','Tekne, rota ve hava koşullarını doğrula','supplier',10),
 ('yacht','embarkation','during','Yolcu kabulü ve seyir başlangıcını kaydet','supplier',20),
 ('yacht','disembarkation','after','İniş ve sefer kapanışını tamamla','supplier',30),
 ('tour','departure_pack','before','Program, buluşma yeri ve rehberi doğrula','supplier',10),
 ('tour','attendance','during','Katılım ve tur değişikliklerini izle','supplier',20),
 ('tour','completion','after','Tur gerçekleşmesini ve geri bildirimi kaydet','supplier',30),
 ('activity','slot_ready','before','Seans, ekipman ve güvenlik bilgisini doğrula','supplier',10),
 ('activity','participation','during','Katılımı ve etkinlik durumunu kaydet','supplier',20),
 ('activity','followup','after','Etkinlik sonrası geri bildirimi izle','supplier',30),
 ('flight','ticket_issue','before','Bilet, PNR ve yolcu bilgilerini doğrula','supplier',10),
 ('flight','departure_watch','during','Uçuş değişikliklerini ve binişi izle','supplier',20),
 ('flight','arrival','after','Varış ve aksaklık taleplerini kapat','supplier',30),
 ('car','vehicle_ready','before','Araç, sigorta ve teslim noktasını doğrula','supplier',10),
 ('car','handover','during','Araç teslimi ve hasar kaydını tamamla','supplier',20),
 ('car','return','after','İade, yakıt ve depozito kontrolünü tamamla','supplier',30),
 ('cruise','cabin_docs','before','Kabin, bilet ve liman belgelerini doğrula','supplier',10),
 ('cruise','boarding','during','Gemiye biniş ve rota değişikliğini izle','supplier',20),
 ('cruise','disembark','after','İniş ve sefer kapanışını tamamla','supplier',30),
 ('pilgrimage','pilgrim_docs','before','Vize, sağlık ve kafile belgelerini doğrula','supplier',10),
 ('pilgrimage','group_watch','during','Kafile ve rehber durumunu izle','supplier',20),
 ('pilgrimage','return','after','Dönüş ve belge kapanışını tamamla','supplier',30),
 ('visa','application_docs','before','Başvuru ve evrak kontrolünü tamamla','supplier',10),
 ('visa','appointment','during','Randevu ve konsolosluk sürecini izle','supplier',20),
 ('visa','result_delivery','after','Sonucu ve pasaport teslimini kaydet','supplier',30),
 ('ferry','ticket_check','before','Bilet, sefer ve liman bilgisini doğrula','supplier',10),
 ('ferry','boarding','during','Biniş ve sefer değişikliğini izle','supplier',20),
 ('ferry','arrival','after','Varış ve aksaklık talebini kapat','supplier',30),
 ('transfer','pickup_check','before','Uçuş, araç ve karşılama noktasını doğrula','supplier',10),
 ('transfer','pickup','during','Yolcu karşılamayı ve sürücü durumunu izle','supplier',20),
 ('transfer','dropoff','after','Bırakma ve hizmet kapanışını kaydet','supplier',30),
 ('beach','seat_ready','before','Şezlong, alan ve saat bilgisini doğrula','supplier',10),
 ('beach','admission','during','Giriş ve kullanım durumunu izle','supplier',20),
 ('beach','close','after','Kullanım bitişini kaydet','supplier',30),
 ('cinema','seat_ticket','before','Seans, koltuk ve bileti doğrula','supplier',10),
 ('cinema','admission','during','Bilet okutma ve giriş durumunu izle','supplier',20),
 ('cinema','close','after','Seans kapanışını kaydet','supplier',30),
 ('event','event_ticket','before','Etkinlik, bilet ve giriş bilgisini doğrula','supplier',10),
 ('event','admission','during','Giriş ve program değişikliklerini izle','supplier',20),
 ('event','close','after','Etkinlik kapanışı ve geri bildirimi kaydet','supplier',30),
 ('restaurant','table_confirm','before','Masa, saat ve özel isteği doğrula','supplier',10),
 ('restaurant','seating','during','Misafir kabulü ve masa durumunu izle','supplier',20),
 ('restaurant','close','after','Hizmet kapanışı ve geri bildirimi kaydet','supplier',30),
 ('bus','seat_ticket','before','Koltuk, sefer ve bileti doğrula','supplier',10),
 ('bus','boarding','during','Biniş ve sefer değişikliğini izle','supplier',20),
 ('bus','arrival','after','Varış ve aksaklık talebini kapat','supplier',30)
ON CONFLICT(category_code,step_key) DO NOTHING;

